CREATE TABLE BOOK (
ISBN VARCHAR(50) NOT NULL,
BOOK_NAME VARCHAR(100) NOT NULL,
PRICE INT,
PRIMARY KEY (ISBN)
);

CREATE TABLE BOOK_STOCK (
ISBN VARCHAR(50) NOT NULL,
STOCK INT NOT NULL,
PRIMARY KEY (ISBN),
CONSTRAINT positive_stock CHECK (STOCK >= 0)
);

CREATE TABLE ACCOUNT (
USERNAME VARCHAR(50) NOT NULL,
BALANCE INT NOT NULL,
PRIMARY KEY (USERNAME),
CONSTRAINT positive_balance CHECK (BALANCE >= 0)
);